# Preload images to be used
preload = ~/wallpapers/sea-sunset-clouds-sky-5k-zh.jpg
preload = ~/wallpapers/simon-rae-418042-unsplash.jpg

# Set wallpaper for all monitors
# wallpaper = , ~/Pictures/backgrounds/mountain.png

# Set wallpaper for a specific monitor
# wallpaper = DP-1, ~/Pictures/backgrounds/forest.png

# You can specify the fitting mode with "contain:", "tile:", etc.
# wallpaper = , contain:~/Pictures/backgrounds/mountain.png
